name: Build
run-name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'
        - run: npm ci
        - run: npm run build
        - run: npm run build:pdf
        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "🤖 Build"
            commit_options: '--no-verify --signoff'
            repository: 'git@github.com:frodi-karlsson/frodi-karlsson.github.io.git'
            file_pattern: '*.pdf'
            branch: 'main'
